[package]
name = "cryptographic-message-syntax"
version = "0.20.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "A pure Rust implementation of Crypographic Message Syntax (RFC 5652)"
keywords = ["cms", "rfc5652", "apple", "codesign"]
homepage = "https://github.com/indygreg/cryptography-rs"
repository = "https://github.com/indygreg/cryptography-rs.git"
readme = "README.md"

[dependencies]
bcder = "0.7.1"
bytes = "1.0.1"
chrono = "0.4.23"
hex = "0.4.3"
pem = "1.0.2"
reqwest = { version = "0.11.13", default-features = false, features = ["blocking", "rustls-tls"] }
ring = "0.16.20"
signature = "1.3.2"

[dependencies.x509-certificate]
path = "../x509-certificate"
version = "0.17.0-pre"
features = ["test"]
